### ISSUE TITLE
Getting Facebook Friends

### ISSUE THREAD

**Issue by carlpeaslee** [carlpeaslee/bouncetribe#10]
Here is the file where we are asking for initial scopes. It looks like we are getting facebook friends from users:

https://github.com/BounceTribe/bouncetribe/blob/d7972e27fdcab7ad4e089ae0668e3368e0a04f05/src/utils/auth.js#L77

And here is an example where we are requesting some information about a user's facebook friends:

https://github.com/BounceTribe/bouncetribe/blob/d7972e27fdcab7ad4e089ae0668e3368e0a04f05/src/utils/graphql.js#L130-L177

**Comment by JakeIwen** [comment]
I was unable to acquire an entire friends list. It may be that facebook does the comparison and returns BT friends that are also FB friends. 
Regardless, this not a problem because today Ryan and I discussed this. He intended for this to be a tribe invite for BT-using FB friends, not an invite to BT.

Heres is the root 'profile' of what the FB query returns for reference.

![image](https://user-images.githubusercontent.com/20415982/31420877-c4cba29a-ae09-11e7-9071-58f9267adbc7.png)

**Comment by RPowerHimself** [comment]
Yeah we only need to find mutual friends on Facebook, so the data we have now is fine. We'll use email invites to allow users to invite people NOT using the app.
